### ISSUE TITLE
Optionally gather the SC tag from a scraps.bam file when loading the pbi

### ISSUE THREAD

**Issue by evolvedmicrobe** [PacificBiosciences/pbbamr#2]
Feature request by Onureena.

**Comment by dalexander** [comment]
What exactly does this mean?  The SC tag isn't represended in an index anywhere, to my knowledge---you would have to parse the whole file.

**Comment by evolvedmicrobe** [comment]
Yeah, with certain options enabled we slurp up not only the index but also parse the entire file for values (like the SNR's of the four channels).

**Comment by evolvedmicrobe** [comment]
Fixed with 105832f51d6d4af15fd0c8ca2b50e69b1d5b8109
