### ISSUE TITLE
need dataset support

### ISSUE THREAD

**Issue by dalexander** [PacificBiosciences/pbbamr#3]
Secondary primarily operates on "datasets" now, rather than BAM files directly.  In practice, this means that the end result of a secondary job is usually a dataset XML referring to multiple output BAMs and 
"applying" filters to them---we avoid needless heavyweight file-merges and filters on BAMs where possible.

We should start thinking about what this means for `pbbamr`.  The underlying `pbbam` lib speaks dataset natively, so the capabilities are all there.  But what does it mean for loading the pbi index, for example?  Do we want to have some kind of "virtual" pbi index that can be fulfilled from a dataset?  I could imagine many ways of achieving this.

**Comment by evolvedmicrobe** [comment]
Does pbbam not provide a virtual pbi index already?  How does it currently handle this?

**Comment by evolvedmicrobe** [comment]
@dalexander : looking at datasets now, the support in pbbam actually seems somewhat limited.  When you say that "Secondary primarily operates on datasets now" how are most people performing that operation?  pbcore seems to use a totally different approach than pbbam, and I am not sure what our primary API to datasets is.

**Comment by dalexander** [comment]
pbbam has great support for datasets.  what are you looking for?

yes, pbcore is different.  I think the APIs fit their respective languages pretty well.

**Comment by evolvedmicrobe** [comment]
Now fixed.  loadPBI can now load a virtual index over data frames, and individual alignments can be queried from that directly using `loadAlnsFromnIndex`
