### ISSUE TITLE
Setup CI test in Circle or travis

### ISSUE THREAD

**Issue by mpkocher** [PacificBiosciences/pbbamr#5]
It would be useful to share CI test setup for R code.

I asked MJ to try to get something working for for [pbcommand as well](Setup CI test in Circle or travis).

**Comment by dalexander** [comment]
Yes, this is planned

**Comment by evolvedmicrobe** [comment]
@mpkocher, are you using pbbamr?

**Comment by mhsieh** [comment]
Let me know if you need me to look into this as well.

**Comment by mpkocher** [comment]
@evolvedmicrobe I kicked the tires on an early version and It worked nicely 👍 

I was using very helloworld-ish tasks in pbcommandR to mechanistically test pipeline running. The impeding step to running a real pipeline with pbbamr was dataset support.

**Comment by dalexander** [comment]
I took a stab at this here: #7 , I think we should merge this for now and then we can refine it as we go

**Comment by dalexander** [comment]
This is provisionally solved, but the tests aren't yet being run

**Comment by evolvedmicrobe** [comment]
I think the tests are easiest to run on Travis, but will try to get something working on CircleCI later

**Comment by evolvedmicrobe** [comment]
Just setup testing, and checked that it fails when it should and passes when it should.
